apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/deployment.yml

namespace: products

images:
- name: andreaps/products-api
  newName: andreaps/products-api
  newTag: f930442fbfcdb58bb0df2b7101a0ab147b38d461
