apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/deployment.yml

namespace: products-api

images:
- name: andreaps/products-api
  newName: andreaps/products-api
  newTag: 40ee3e4d87cdc5819abe2ecfc64a4a5b698ed30a
