apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/deployment.yml

namespace: products-api

images:
- name: andreaps/products-api
  newName: andreaps/products-api
  newTag: ff8fc1ee06a794c09835073656df8b471a55a367
