apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  selector:
    matchLabels:
      app: products-api
  replicas: 5
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
      - name: products-api
        image: andreaps/products-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  selector:
    app: products-api
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080